package com.cn.uca.config;

public class MyConfig {
	// 总接口
	public static final String url = "http://www.szyouka.com:8080/youkatravel/api/";
//	public static final String url = "http://192.168.1.103:80/youkatravel/api/";
	public static final String sendCode = url+"user/query/sendSMS.do";//发送短信验证码
	public static final String getWeChatToken = "https://api.weixin.qq.com/sns/oauth2/access_token";//获取微信token
	public static final String weChatLogin = url+"/user/query/userLogin_weixin.do";//微信登录
	public static final String createZfbOrder = url + "user/update/createZfbOrder.do";//创建支付包订单
	public static final String getAuthInfo = url + "user/query/zfbAuthInfo.do";//获取支付宝登录信息
	public static final String userLogin = url  + "user/query/userLogin_zfb.do";//支付宝登录
	public static final String uplodePic = url+"user/update/uploadHeadPortrait.do";//上传用户头像
	public static final String getUserBriefInfo = url+"user/query/getUserBriefInfo.do";//获取简单用户信息
	public static final String setUserInfo = url+"user/update/setUserInfo.do";//修改用户信息
	public static final String phoneLogin = url+"user/query/phone_login.do"; //手机用户登录
	public static final String phoneRegister = url+"user/update/userRegister.do";//手机号注册
	public static final String getUserInfo = url+"user/query/getUserInfo.do";//获取用户信息
	public static final String getUserPush = url+"user/query/getUserSetting.do";//获取用户推送设置
	public static final String setUserPush = url+"user/update/updateUserSetting.do";//用户是否推送
	public static final String updatePassword = url+"user/update/modifyPassword.do";//修改用户密码
	public static final String forgetPassword = url+"user/update/forgotPassword.do";//忘记密码
	public static final String submitIdentity = url+"user/update/submitIdentityExamine.do";//用户身份认证
	public static final String getEscortRecords = url+"escort/query/getEscortRecords.do";//获取伴游
	public static final String getEscortRecordInfo = url+"escort/query/getEscortRecordInfo.do";//获取伴游详情
	public static final String addLine = url+"escort/update/insertRoute.do";//添加伴游路线
	public static final String getAllLine = url+"escort/query/getAllRoute.do";//获取伴游路线
	public static final String deleteLine = url+"escort/update/deleteRoute.do";//删除路线
	public static final String addLinePoint = url+"escort/update/addPlaces.do";//添加路线点
	public static final String updateLineName = url+"escort/update/updateRoute.do";//修改路线名
    public static final String getWallet = url+"user/query/queryBalance.do";//获取用户余额
	public static final String getReleaseInfo = url+"escort/query/getReleaseInfo.do";//获取发布页面数据
	public static final String collectionEscortRecord = url+"escort/update/collectionEscortRecord.do";//收藏/取消伴游
	public static final String getCarouselFigures = url+ "home/query/getCarouselFigures.do";//获取轮播图
	public static final String releaseEscortRecord = url+"escort/update/releaseEscortRecord.do";//发布伴游
	public static final String newAppVersionAndroid = url+"home/query/newAppVersionAndroid.do";//版本更新
	public static final String getUserState = url+"user/query/getUserState.do";//获取用户状态
	public static final String fastLogin = url+"user/query/fastLogin.do";//快速登录
	public static final String getEscortInfo = url+"escort/query/getEscortInfo.do";//获取约咖用户信息
	public static final String photo = "http://www.szyouka.com:8080/youkatravel/api/util/pictureCompression.do?pictureUrl=";//图片压缩
	public static final String getZhouBianTravel = url+"travel/query/getZhouBianTravel.do";//获取周边游
	public static final String getJuiDian = url+"travel/query/getJuiDian.do";//获取周边游酒店
	public static final String getGuoNeiYou = url+"travel/query/getGuoNeiYou.do";//获取国内游
	public static final String getMiYeuYou = url+"travel/query/getMiYeuYou.do";//获取蜜月游
	public static final String getChuJingYou = url+"travel/query/getChuJingYou.do";//获取出境游
	public static final String getTicket = url+"travel/query/getTicket.do";//获取景区门票
	public static final String getHotTicket = url+"travel/query/getHotTicket.do";//获取热门景区门票
	public static final String getScenicSpotCity = url+"travel/query/getScenicSpotCity.do";//获取热门城市景区门票
	public static final String getScenicSpot = url+"travel/query/getScenicSpot.do";//获取城市景区门票
	public static final String cpyGetCityRaiders = url+"travel/query/cpyGetCityRaiders.do";//城市攻略
	public static final String getCityRaidersInfo = url+"travel/query/getCityRaidersInfo.do";//获取攻略详情
	public static final String openLife = url + "life/update/openLife.do";//开启余生
	public static final String getLifeDays = url +"life/query/getLifeDays.do";//获取余生天数的记录
	public static final String getLifeMonths = url +"life/query/getLifeMonths.do";//获取余生月数的记录
	public static final String getLifeHistorical = url +"life/query/getLifeHistorical.do";//获取余生痕迹
	public static final String addLifeDayEvent = url+"life/update/addLifeDayEvent.do";//添加余生天记录
    public static final String addLifeMonthEvent = url+"life/update/addLifeMonthEvent.do";//添加余生月记录
	public static final String getFootprintChina = url+"footprint/query/getFootprintChina.do";//获取用户足迹以及用户城市记录
    public static final String loadMoreFootprintChina = url+"footprint/query/getFootprintChinaCity.do";;//刷新用户足迹
	public static final String getCityName = url+"footprint/query/getCity.do";//获取足迹省份下的城市
	public static final String addFootprintChina = url+"footprint/update/addFootprintChina.do";//添加用户足迹
	public static final String getFootprintWorld = url+"footprint/query/getFootprintWorld.do";//.获取世界足迹
	public static final String addFootprintWorld = url+"footprint/update/addFootprintWorld.do";//添加世界足迹
	public static final String loadMoreFoodPrintWorld = url+"footprint/query/getFootprintWorldCountry.do";//刷新世界足迹
	public static final String uploadCoverPicture = url+"escort/update/uploadCoverPicture.do";//.上传/修改游约咖面图片(约咖)
	public static final String getCoverPicture = url+"escort/query/getCoverPicture.do";//获取用户游咖所有背景图片
	public static final String deleteCoverPicture = url+"escort/update/deleteCoverPicture.do";//删除用户图片
	public static final String getIdCardUrl = url+"user/query/getIdCardUrl.do";//获取芝麻信用url
	public static final String feedback = url+"home/query/feedback.do";//app反馈
	public static final String purchaseCityRaiders = url+"travel/update/purchaseCityRaiders.do";//购买一元攻略
    public static final String orderPayment = url+"/user/update/orderPayment.do";//支付订单
	public static final String getUserOrder = url +"user/query/getUserOrder.do";//获取用户订单
    public static final String createWeiXinOrder = url+"user/update/createWeiXinOrder.do";//创建微信订单
	public static final String queryWeiXinOrderState = url+"query/queryWeiXinOrderState.do";//验证微信支付是否成功
	public static final String userClock = url+"user/update/userClock.do";//用户签到
	public static final String getPurseRecords = url + "user/query/getPurseRecords.do";//获取账号明细
	public static final String getUserClock = url+"user/query/getUserClock.do";//加载用户签到信息
	public static final String getConfirmCoffee = url+"escort/query/getConfirmCoffee.do";//伴游确认订单数据
	public static final String purchaseEscor = url +"escort/update/purchaseEscor.do";//订购伴游
	public static final String calculationPrice = url+"escort/query/calculationPrice.do";//计算约咖价格
	public static final String getMyEscortOrder = url+"escort/query/getMyEscortOrder.do";//获取我的接单
	public static final String getReleaseEscortRecords = url + "escort/query/getReleaseEscortRecords.do";//领咖我的发布
	public static final String getEscprtRecordUsers = url +"escort/query/getEscprtRecordUsers.do";//获取陪游的所有用户订单
	public static final String collectionRaiders = url + "travel/update/collectionRaiders.do";//取消收藏攻略
	public static final String getMyRaiders = url +"travel/query/getMyRaiders.do";//获取攻略收藏或购买
	public static final String acceptanceEscortUser = url+"escort/update/acceptanceEscortUser.do";//伴游接单/拒接
	public static final String travleEscortBack = url +"escort/update/travleEscortBack.do";//游咖用户申请退单
	public static final String getTravelEscortBack = url +"escort/query/getTravelEscortBack.do";//领咖获取游咖申请退单信息
	public static final String approvalTravelEscortBack = url +"escort/update/approvalTravelEscortBack.do";//领咖端审批游咖退单
	public static final String getShare = url + "user/query/getShare.do";//分享
	public static final String getRongInfo = url + "user/query/getUserInfos.do";//获取融云用户信息
	public static final String getCafeLabel = url + "citycafe/query/getCafeLabel.do";//获取同城咖发布时的标签
	public static final String addUserCard = url + "citycafe/update/addUserCard.do";//添加用户名片
	public static final String getUserCard = url + "citycafe/query/getUserCard.do";//获取用户名片
    public static final String getCityCafe = url + "citycafe/query/getCityCafe.do";//获取同城咖
	public static final String getCityCafeInfo = url + "citycafe/query/getCityCafeInfo.do";//获取同城咖详情
	public static final String getTickets = url + "citycafe/query/getTickets.do";//获取同城咖购票
	public static final String orderTicket = url + "citycafe/update/orderTicket.do";//购买同城咖
	public static final String releaseCityCafe = url + "citycafe/update/releaseCityCafe.do";//发布同城咖
	public static final String getMyTicket = url + "citycafe/query/getMyTicket.do";//获取我的门票
	public static final String getUserTickets = url +"citycafe/query/getUserTickets.do";//获取门票码
	public static final String getCollectionCityCafe = url + "citycafe/query/getCollectionCityCafe.do";//获取用户收藏的同城咖
	public static final String getMyCityCafe = url + "citycafe/query/getMyCityCafe.do";//获取我的活动
	public static final String getTicketApproval = url +"citycafe/query/getTicketApproval.do";//获取报名审核
	public static final String getRefundTicket = url + "citycafe/query/getRefundTicket.do";//获取退票审核
	public static final String approvalTicket = url + "citycafe/update/approvalTicket.do";//报名审核
	public static final String approvalRefundTicket = url + "citycafe/update/approvalRefundTicket.do";//退票审核
	public static final String getSettlement  = url + "citycafe/query/getSettlement.do";//获取同城咖结算
	public static final String settlement = url + "citycafe/update/settlement.do";//同城咖结算
	public static final String cityCafeAdmin = url + "citycafe/query/cityCafeAdmin.do";//同城咖活动管理
	public static final String staSusCityCafe = url +"citycafe/update/staSusCityCafe.do";//开始或暂停同城咖售票
	public static final String collectionCityCafe = url + "citycafe/update/collectionCityCafe.do";//收藏/取消收藏同城咖
	public static final String getCafeUser = url + "citycafe/query/getCafeUser.do";//获取同城咖发布者卡票信息
	/**
	 * 旅拍
	 */
	public static final String becomeMerchant = url+"tripshoot/update/becomeMerchant.do";//商家入驻
	public static final String getMerchantInfo = url + "tripshoot/query/getMerchantInfo.do";//获取商家信息
	public static final String gerAddress = url +"tripshoot/query/gerAddress.do";//获取商家地址
	public static final String getStyleLable = url + "tripshoot/query/getStyleLable.do";//获取旅拍样式标签
    public static final String getTs = url + "tripshoot/query/getTs.do";//获取旅拍商品
    public static final String getMerchants = url + "tripshoot/query/getMerchants.do";//获取旅拍商户
	public static final String releaseTripShoot = url + "tripshoot/update/releaseTripShoot.do";//发布旅拍
	public static final String getCommodityInfo = url + "tripshoot/query/getTsInfo.do";//获取商品详细信息
	public static final String getMerInfo = url + "tripshoot/query/getMerInfo.do";//获取商家信息
	public static final String getMerAllPic = url + "tripshoot/query/getMerAllPic.do";//获取旅拍商户相册图片
    public static final String getTsDate = url + "tripshoot/query/getTsDate.do";//获取旅拍商品行程
	public static final String collectionTs = url + "tripshoot/update/collectionTs.do";//收藏或取消收藏旅拍商品
	public static final String followMerchant = url + "tripshoot/update/followMerchant.do";//关注/取消关注旅拍商户
	public static final String createTsOrder = url + "tripshoot/update/createTsOrder.do";//预定商品
	public static final String updateTeam = url + "tripshoot/update/updateTeam.do";//增删改团队
	public static final String getTeam = url + "tripshoot/query/getTeam.do";//获取团队
	public static final String getFollowMers = url + "tripshoot/query/getFollowMers.do";//获取用户收藏的旅拍商户
	public static final String getCollTs = url + "tripshoot/query/getCollTs.do";//获取用户收藏的旅拍商品
	public static final String getMerchantAlbum = url + "tripshoot/query/getMerchantAlbum.do";//获取商家相册
	public static final String getAlbumPicture = url + "tripshoot/query/getAlbumPicture.do";//获取相册中的图片
	public static final String getMyTs = url + "tripshoot/query/getMyTs.do";//获取旅拍商户发布的商品
	public static final String getTsOrders = url + "tripshoot/query/getTsOrders.do";//获取商家旅拍订单
	public static final String hotspot = url +"tripshoot/update/hotspot.do";//设置旅拍商品推荐
	public static final String saveDetails = url + "escort/update/saveDetails.do";//约咖详情
	public static final String upLoShelves = url +"tripshoot/update/upLoShelves.do";//旅拍商品上架&&下架
 }